name = "EvolvingDomains"
uuid = "f9bd8acb-b7a8-42b3-8348-bb9bbfd76943"
authors = ["Naoufel Cresson"]
version = "0.1.0"
[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapEmbedded = "8838a6a3-0006-4405-b874-385995508d5d"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
[compat]
julia = "1.9"
Gridap = "0.18"
GridapEmbedded = "0.9"
GridapSolvers = "0.6"
StaticArrays = "1"
[extras]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LevelSetMethods = "4d80b4c3-6b06-4b5f-9c79-e5b8baaaca5f"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
[targets]
test = ["Test", "LevelSetMethods", "Plots", "Interpolations", "NearestNeighbors"]