name = "EvolvingDomains"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Your Name"]
version = "0.1.0"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapEmbedded = "8b98e015-2b9d-4b06-9d4c-e0a9e4c9e7ba"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LevelSetMethods = "4d80b4c3-6b06-4b5f-9c79-e5b8baaaca5f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Test", "LevelSetMethods", "Plots"]

